name: Permit2 swap tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-permit2-swap:
    uses: ./.github/workflows/tests-template.yml
    with:
      make-command: test-permit2-swap
    secrets: inherit