name: Permit2 mint tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-permit2-mint:
    uses: ./.github/workflows/tests-template.yml
    with:
      make-command: test-permit2-mint
    secrets: inherit