name: Permit2 redeem tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-permit2-redeem:
    uses: ./.github/workflows/tests-template.yml
    with:
      make-command: test-permit2-redeem
    secrets: inherit